#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/SymPub-Thin.ufo    &
psfnormalize -p checkfix=fix source/masters/SymPub-Regular.ufo &
psfnormalize -p checkfix=fix source/masters/SymPub-Black.ufo   &
wait

echo "-----Rebuilding composites..."
psfbuildcomp -i source/composites.txt -c -n source/masters/SymPub-Thin.ufo -p backup=False
psfbuildcomp -i source/composites.txt -c -n source/masters/SymPub-Regular.ufo -p backup=False
psfbuildcomp -i source/composites.txt -c -n source/masters/SymPub-Black.ufo -p backup=False

# Uncomment the following lines to rebuild reversed composites.
# Unlike the other composites these glyphs then need to be decomposed in a font design app,
# and have the correct path direction applied. This is necessary to properly construct the
# white-on-black effects in the circled numbers and letters. Running this again will undo
# any manual decomposition and path direction changes!
echo "-----Rebuilding reversed composites - will need post-processing..."
psfbuildcomp -i source/compositesreversed.txt -c -n source/masters/SymPub-Thin.ufo -p backup=False
psfbuildcomp -i source/compositesreversed.txt -c -n source/masters/SymPub-Regular.ufo -p backup=False
psfbuildcomp -i source/compositesreversed.txt -c -n source/masters/SymPub-Black.ufo -p backup=False

# Update glyph order in Regular UFO
psfsetglyphorder --header sort_final -i source/glyph_data.csv source/masters/SymPub-Regular.ufo

# Update production names in Regular UFO
psfsetpsnames -i source/glyph_data.csv source/masters/SymPub-Regular.ufo

# Sync glyph orders, psnames, and other metadata
psfsyncmasters -q source/SymPub.designspace

# Create WOFF metadata file
psfmakewoffmetadata -n sympub -i org.sil.fonts -o source/SymPub-WOFF-metadata.xml source/masters/SymPub-Regular.ufo
