#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/SymPub-Thin.ufo    &
psfnormalize -p checkfix=fix source/masters/SymPub-Regular.ufo &
psfnormalize -p checkfix=fix source/masters/SymPub-Black.ufo   &
wait

# Update glyph order in Regular UFO
psfsetglyphorder --header sort_final -i source/glyph_data.csv source/masters/SymPub-Regular.ufo

# Update production names in Regular UFO
psfsetpsnames -i source/glyph_data.csv source/masters/SymPub-Regular.ufo

# Sync glyph orders, psnames, and other metadata
psfsyncmasters -q source/SymPub.designspace

# Create WOFF metadata file
psfmakewoffmetadata -n sympub -i org.sil.fonts -o source/SymPub-WOFF-metadata.xml source/masters/SymPub-Regular.ufo
